### ISSUE TITLE
2.0.0 throws error

### ISSUE THREAD

**Issue by maxxscho** [sindresorhus/gulp-autoprefixer#20]
Hey,
I'm using gulp-ruby-sass and if I add gulp-autoprefixer, I get the following error
```
write style.css.map

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: /Users/myfolderstructure/style.css.map:3:1: Unknown word
```
With sourcemaps and without sourcemaps.

All versions under 2.0.0 are working fine.

**Comment by xmlking** [comment]
I am switching from gulp-ruby-sass `0.7.1 -> 1.0.0-alpha` , gulp-autoprefixer `1.0.1->2.0.0`,
gulp-sourcemaps `1.3.0` and having following issues and looking for solution.
 
1. Error when set `sourcemapPath: '.'`  in 1.0.0-alpha recipe.
2. Where should I add `sourcemaps.init()` in 1.0.0-alpha recipe?
3. `watch` task was only compiling changed files before, but with  1.0.0-alpha recipe all sass files are compiled even a singe sass file is changed. 

```
Environment  : Windows 
gem -v           : 2.0.15
ruby -v           : ruby 2.0.0p481 (2014-05-08) [x64-mingw32]
sass -v           : Sass 3.4.9 (Selective Steve)
node -v          : v0.10.28
gulp -v           : 3.8.7
```
```js
import {ErrorHandler} from './errors';

let sass        = require('gulp-ruby-sass'),
  sourcemaps  = require('gulp-sourcemaps'),
  filter      = require('gulp-grep-stream'),
  browserSync = require('browser-sync'),
  autoprefixer= require('gulp-autoprefixer'),
  reload      = browserSync.reload;

export default function styles(gulp, cfg, args) {
  'use strict';
  gulp.task('styles_0.7.1"', () => {
    return gulp.src(cfg.paths.sass)
      .pipe(sourcemaps.init())
      .pipe(sass({
        style: 'expanded',
        precision: 10,
        sourcemap: (!optimize),
        sourcemapPath: '.',
        loadPath: ['bower_components/bourbon/dist', 'bower_components/compass-mixins/lib']
      }))
      .on('error', ErrorHandler.onError)
      .pipe(autoprefixer(cfg.autoprefixer))
      .pipe(sourcemaps.write('.'))
      .pipe(gulp.dest('.tmp'))
      .pipe(filter('**/*.css'))
      .pipe(reload({stream: true}));
  });

  gulp.task('styles', () => {
    return sass('app', {
      style: 'expanded',
      precision: 10,
      sourcemap: (!optimize),
      // sourcemapPath: '.',  <-- error when set with 1.0.0-alpha
      loadPath: ['bower_components/bourbon/dist', 'bower_components/compass-mixins/lib']
    })
    .on('error', ErrorHandler.onError)
    .pipe(autoprefixer(cfg.autoprefixer))
    .pipe(sourcemaps.write('.', {
      includeContent: false,
      sourceRoot: '.'
    }))
    .pipe(gulp.dest('.tmp'))
    .pipe(filter('**/*.css'))
    .pipe(reload({stream: true}));
  });
}

```

```js
export default function watch(gulp, cfg, env) {
  'use strict';
  gulp.task('watch', ['styles', 'scripts'], function () {
    gulp.watch('app/**/*.scss', ['styles']);
    gulp.watch(cfg.paths.scripts, ['transpile']);
    gulp.watch(cfg.paths.images, ['images']);
    gulp.watch('bower.json', ['wiredep']);
  });
}
```

**Comment by robwierzbowski** [comment]
> Where should I add sourcemaps.init() in 1.0.0-alpha recipe?

gulp-ruby-sass does it itself, I'll add a note to the new documentation.

> watch task was only compiling changed files before, but with 1.0.0-alpha recipe all sass files are compiled even a singe sass file is changed.

My current plan is to try and get Sass caching to work, not to use changed / other iterative build plugins. If you check on the 1.0 PR that's still an unchecked item on TODO.

>  Error when set sourcemapPath: '.' in 1.0.0-alpha recipe.

There is no sourcemapPath in 1.0.0-alpha. Please read the 1.0 sourcemapping recipes.

**Comment by Brendonwbrown** [comment]
@visualcookie Please post results. I'd love to use sourcemaps, but with autoprefixer killing them off, I'm fine without.

**Comment by thewinger** [comment]
I'm going crazy. I've been reading but my knowledge is short.

npm -v gulp-ruby-sass --> 1.4.3

gulpfile.js 
```javascript
// Sass Compiling
gulp.task('sass', function() {
    return sass('src/scss/main.scss')
    .pipe(plumber())
    .pipe(sass({ style: 'expanded', sourcemap: true }))
    .pipe(autoprefixer({
        browsers: ['last 2 versions', 'safari 5', 'ie 8', 'ie 9', 'opera 12.1'],
        cascade: false
        }))
    .pipe(gulp.dest(dest + 'css'))
    .pipe(connect.reload())
    .pipe(notify({ message: 'Sass task completed' }));
}); 
```

$ gulp sass --verbose OUTPUT
```
[05:30:56] Starting 'sass'...
[05:30:56] gulp-ruby-sass: Running command: sass --sourcemap=none src/scss/main.scss /var/folders/vz/sxt9fr5176qb7jrw49yz5f880000gn/T/gulp-ruby-sass/main.css
[05:30:56] 'sass' errored after 36 ms Arguments to path.join must be strings
[05:30:57] Finished 'scripts' after 69 ms
[05:30:57] gulp-ruby-sass stderr: OptionParser::NeedlessArgument: needless argument: --sourcemap=none
  Use --trace for backtrace.
```

¿What am I doing wrong?

**Comment by UltCombo** [comment]
@thewinger `1.4.3` is your npm version, not gulp-ruby-sass's btw. But judging by the code sample, looks like you're on a gulp-ruby-sass 1.0 alpha release.

And the issue is rather apparent, you have `sass()` twice in your pipeline -- gulp-ruby-sass 1.0 replaces `gulp.src()` and emits already compiled css so you shouldn't be piping to `sass()` again. See the [docs' examples](https://github.com/sindresorhus/gulp-ruby-sass/tree/rw/1.0#usage).

**Comment by UltCombo** [comment]
@robwierzbowski perhaps it would be worth to add an autoprefix recipe to grs? Looks like this an extremely common use case and many people are getting confused about the grs 1.0.0 upgrade.

**Comment by robwierzbowski** [comment]
For sure. I'll be working on docs and small errors tomorrow. I'll add a
recipe in and push changes up right away.

Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by thewinger** [comment]
Deleted the line
```
.pipe(sass({ style: 'expanded', sourcemap: true }))
```

But still having the same output
```
gulp-ruby-sass: Running command: sass --sourcemap=none src/scss/main.scss /var/folders/vz/sxt9fr5176qb7jrw49yz5f880000gn/T/gulp-ruby-sass/main.css
[12:39:26] gulp-ruby-sass stderr: OptionParser::NeedlessArgument: needless argument: --sourcemap=none
```

**Comment by UltCombo** [comment]
@thewinger that's odd, theoretically that should be fixed in 1.0.0-alpha (see https://github.com/sindresorhus/gulp-ruby-sass/issues/145)

**Comment by thewinger** [comment]
Having the gulpfile as

```javascript
gulp.task('sass', function() {
    return sass('src/scss/main.scss')
    .pipe(plumber())
    .pipe(gulp.dest('dist/css'))
    .pipe(connect.reload())
    .pipe(notify({ message: 'Sass task completed' }));
});
```

Still having the same output. I'm still struggling with the solution. 
I've even done the deleting the npm_modules folder as said here https://github.com/sindresorhus/gulp-ruby-sass/issues/145#issuecomment-68270492

**Comment by smlombardi** [comment]
As mentioned above, I have been using this without error for over a month now, on more than one project:

````
gulp.task('styles', function() {
  return sass('app/sass/main.scss', { sourcemap: true })
  .pipe(plumber())
  .pipe(autoprefixer({
    browsers: ['last 2 versions', 'ios 6', 'android 4']
  }))
  .pipe(sourcemaps.write('maps', {
    includeContent: false,
    sourceRoot: '/source'
  }))
  .pipe(gulp.dest('app/css'))
  .pipe(filter('**/*.css'))
  .pipe(reload({stream:true}))
  .pipe(notify({ message: 'Styles task complete' }));
});
````
package.json shows these relevant plugind
````
    "browser-sync": "^1.7.1",
    "connect": "^2.14.4",
    "del": "^0.1.3",
    "gulp": "^3.6.0",
    "gulp-autoprefixer": "^2.0.0",
    "gulp-connect": "^2.2.0",
    "gulp-csso": "^0.2.6",
    "gulp-filter": "^1.0.2",
    "gulp-notify": "^2.0.1",
    "gulp-plumber": "^0.6.6",
    "gulp-ruby-sass": "^1.0.0-alpha",
    "gulp-sourcemaps": "^1.2.8",
````

**Comment by thewinger** [comment]
Using your code I still have
gulp-ruby-sass stderr: OptionParser::NeedlessArgument: needless argument: --sourcemap=file

**Comment by robwierzbowski** [comment]
@thewinger What version of Sass are you using? `sass -v`

**Comment by thewinger** [comment]
Sass 3.3.10 (Maptastic Maple)

**Comment by UltCombo** [comment]
grs 1.0 only supports the latest stable Sass (3.4)

**Comment by robwierzbowski** [comment]
Yes, IIRC, Sass 3.3 doesn't have the same sourcemap argument. OptionParser is a Ruby library, so that error is coming from Sass. If you must get around it you can do the `"sourcemaps=your_option": true` hack that's been mentioned before, but my suggestion is to upgrade Sass.

**Comment by UltCombo** [comment]
@robwierzbowski I believe it is the other way around. `"sourcemaps=your_option": true` was for grs 0.7.x with Sass 3.4, while @thewinger seems to have grs 1.0 with Sass 3.3

**Comment by robwierzbowski** [comment]
I believe they could still bypass the sourcemap redefinition with the same trick.

**Comment by UltCombo** [comment]
Yes, possibly `'--sourcemap`: false' could do it.

**Comment by UltCombo** [comment]
@robwierzbowski But doesn't grs translate `sourcemap: false` into `--sourcemap=none`?

**Comment by robwierzbowski** [comment]
Ha, while typing an explanation out I realized that wouldn't work at
all. Previously to have no sourcemaps you left off the sourcemap flag, but
1.0 always sets it (to be compatable with Sass 3.4.x). Grs kind of hijacks
the sourcemap option to only pass none or file to sass, because file was
the easiest way to combine Sass and gulp-sourcemaps. So no matter what you
do the sourcemap flag will always be set to file or none.

Upgrading to a compatable Sass or hacking the source is really the only
option.

On Saturday, January 31, 2015, Fabrício Matté <notifications@github.com>
wrote:

> @robwierzbowski <https://github.com/robwierzbowski> But doesn't grs
> translate sourcemap: false into --sourcemap=none?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-autoprefixer/issues/20#issuecomment-72344328>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by thewinger** [comment]
![screen shot 2015-02-01 at 11 21 22](https://cloud.githubusercontent.com/assets/121455/5991766/b3a99e06-aa04-11e4-81ff-c97702a542fd.png)

![screen shot 2015-02-01 at 11 22 03](https://cloud.githubusercontent.com/assets/121455/5991768/bb2c2432-aa04-11e4-981a-db4ec7a5e5de.png)


Updated Sass to 3.4 and still having the same message, but know I do have the main.css at the dist folder so I guess it works even though it still shows the message.

Thank you everyone and sorry for the all the trouble :)

**Comment by silvenon** [comment]
I suggest removing gulp-plumber, this version of gulp-ruby-sass doesn't seem to crash gulp on gulp anymore. Updating Sass and adding a simple `sourcemaps.write()` worked for me like a charm. Here's how I did it:

```js
gulp.task('styles', function () {
  return $.rubySass('app/styles/main.scss', {
    sourcemap: true,
    style: 'expanded',
    precision: 10,
    loadPath: ['.']
  })
    .pipe($.postcss([
      require('autoprefixer-core')({browsers: ['last 1 version']})
    ]))
    .pipe($.sourcemaps.write())
    .pipe(gulp.dest('.tmp/styles'));
});
```

Both Sass and Autoprefixer got correctly mapped.

**Comment by croosen** [comment]
Had this problem just now, adding sourcemaps AFTER prefixer in the pipe works with me.

**Comment by bryanerayner** [comment]
Encountering this error as well


```` js
     /**
     * Process a SASS Styles
     */
    function processSassStyles(fileStream, destFolder) {

        gUtil.log(chalk.cyan('Starting SASS'));

        var sassStream = fileStream
            .pipe(sourcemaps.init())
            .pipe(sass().on('error', sass.logError))
            .pipe(sourcemaps.write('.', { includeContent: false}));

        var autoprefixed = sassStream
            .pipe(sourcemaps.init({ loadMaps: true }))
            .pipe(autoprefixer())
            .pipe(sourcemaps.write('.', { includeContent: false}))
            .pipe(print())
            .pipe(gulp.dest(destFolder));

        

        var minified = autoprefixed
            //.pipe(sourcemaps.init({ loadMaps: true }))
            //.pipe(cssmin())
            //.pipe(sourcemaps.write({ includeContent: false}))
            //.pipe(rename({suffix:'.min'}))
            //.pipe(print())
            //.pipe(sourcemaps.write(destFolder))
            //.pipe(gulp.dest(destFolder));

        // It's done after it's been minified.
        return minified;
    }
````

**Comment by robwierzbowski** [comment]
If you're using gulp ruby sass, update to the latest and look at the doc examples. It's a source adapter, and needs to be set up differently than a standard task.
